# This is a basic workflow to help you get started with Actions

name: 001-manual-input-workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # inputs the workflow accepts
    inputs:
      name:
        description: 'Person to greet'
        default: 'universe'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
